### ISSUE TITLE
Project Euler #10: Summation of primes

### ISSUE THREAD

**Issue by alok760** [alok760/Project-Euler#5]
not passing all the test cases 
https://www.hackerrank.com/contests/projecteuler/challenges/euler010

**Comment by gupta2140** [comment]
Hey, you have to pre-compute all the primes upto 10^6 first. Then finally take inputs, and sum all the pre-computed primes from your list up to n. Hope you can get it from the PR :)

**Comment by alok760** [comment]
> Hey, you have to pre-compute all the primes upto 10^6 first. Then finally take inputs, and sum all the pre-computed primes from your list up to n. Hope you can get it from the PR :)

merged
